version: '3'

services:
  karen-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: karen-api
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=test
