service:
  resource:
    garry: ${garry:192.168.0.100:80/}
    patric: ${patric:192.168.0.101:80/}
    spongebob: ${spongebob}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8086/eureka/}
  instance:
    instance-id: karen-instance-${random.uuid}
spring:
  application:
    name: karen